StokUygulamasıMVC/Controllers/KategoriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StokUygulamasıMVC.Models.Entity;
using PagedList;
using PagedList.Mvc;
using StokUygulamasıMVC.Models.Entity;

namespace StokUygulaması.Controllers
{
    public class KategoriController : Controller
    {
        private ÜrünStokDatabaseEntities ürünStokEntities = new ÜrünStokDatabaseEntities();
        public ActionResult Index(int sayfa = 1)
        {
            var kategoriList = ürünStokEntities.KATEGORILER.ToList().ToPagedList(sayfa, 6);
            return View(kategoriList);
        }
        [HttpGet]
        public ActionResult YeniKategori()
        {
            return View();
        }

        [HttpPost]
        public ActionResult YeniKategori(KATEGORILER yenikategori)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniKategori");
            }

            ürünStokEntities.KATEGORILER.Add(yenikategori);
            ürünStokEntities.SaveChanges();
            return View();
        }
        public ActionResult Sil(int id)
        {
            var bulunanId = ürünStokEntities.KATEGORILER.Find(id);
            ürünStokEntities.KATEGORILER.Remove(bulunanId);
            ürünStokEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult KategoriGetir(int id)
        {
            var bulunanKategori = ürünStokEntities.KATEGORILER.Find(id);
            return View("KategoriGetir", bulunanKategori);
        }
        public ActionResult Guncelle(KATEGORILER kategori)
        {
            var ktg = ürünStokEntities.KATEGORILER.Find(kategori.KATEGORIID);
            ktg.KATEGORIAD = kategori.KATEGORIAD;
            ürünStokEntities.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

StokUygulamasıMVC/Controllers/MusteriController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StokUygulamasıMVC.Models.Entity;
using StokUygulamasıMVC.Models.Entity;

namespace StokUygulaması.Controllers
{
    public class MusteriController : Controller
    {
        ÜrünStokDatabaseEntities ürünStokEntities = new ÜrünStokDatabaseEntities();
        public ActionResult Index(string p)
        
        {
            var degerler = from musteri in ürünStokEntities.MUSTERILER select musteri;
            if(!string.IsNullOrEmpty(p))
            {
                degerler=degerler.Where(m=>m.MUSTERIAD.Contains(p));
            }
            return View(degerler.ToList());

        }
        [HttpGet]
        public ActionResult YeniMüsteri()
        {
            return View();
        }
        [HttpPost]
        public ActionResult YeniMüsteri(MUSTERILER müsteri)
        {
            if (!ModelState.IsValid)
            {
                return View("YeniMüsteri");
            }
            ürünStokEntities.MUSTERILER.Add(müsteri);
            ürünStokEntities.SaveChanges();
            return View();
        }
        public ActionResult Sil(int id)
        {
            var bulunanMusteri = ürünStokEntities.MUSTERILER.Find(id);
            ürünStokEntities.MUSTERILER.Remove(bulunanMusteri);
            ürünStokEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult MusteriGetir(int id)
        {
            var bulunanMusteri = ürünStokEntities.MUSTERILER.Find(id);
            return View("MusteriGuncelle", bulunanMusteri);
        }
        public ActionResult MusteriGuncelle(MUSTERILER musteri)
        {
            var BulunanId = ürünStokEntities.MUSTERILER.Find(musteri.MUSTERIID);
            BulunanId.MUSTERIAD = musteri.MUSTERIAD;
            BulunanId.MUSTERISOYAD = musteri.MUSTERISOYAD;
            ürünStokEntities.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

StokUygulamasıMVC/Controllers/SatisController.cs
using StokUygulamasıMVC.Models.Entity;
using StokUygulamasıMVC.Models.Entity;
using System;
using System.Collections.Generic;
using System.Drawing.Printing;
using System.EnterpriseServices;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace StokUygulaması.Controllers
{
    public class SatisController : Controller
    {
        ÜrünStokDatabaseEntities ürünStokEntities = new ÜrünStokDatabaseEntities();
        public int satısId;
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]//INDEX View içerisinde kullanıyoruz 
        public ActionResult YeniSatis()
        {
            List<SelectListItem> kategoriler = (from i in ürünStokEntities.MUSTERILER.ToList()
                                                select new SelectListItem
                        
                                                {
                                                    Text = i.MUSTERIAD + i.MUSTERISOYAD,
                                                    Value = i.MUSTERIID.ToString()

                                                }).ToList();
            ViewBag.kategori = kategoriler;
            return View();
        }

        [HttpPost]//INDEX View içerisinde kullanıyoruz 
        public ActionResult YeniSatis(SATISLAR satis)
        {
            int i = ürünStokEntities.SATISLAR.Count();
            satis.SATISID = i + 1;
            ürünStokEntities.SATISLAR.Add(satis);
            ürünStokEntities.SaveChanges();
            return RedirectToAction("Index");
        }
    }
}

StokUygulamasıMVC/Controllers/UrunlerController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using StokUygulamasıMVC.Models.Entity;
using PagedList;
using PagedList.Mvc;
using System.Security.Cryptography;
using StokUygulamasıMVC.Models.Entity;

namespace StokUygulaması.Controllers
{
    public class UrunlerController : Controller
    {
        ÜrünStokDatabaseEntities ürünStokEntities = new ÜrünStokDatabaseEntities();
        public ActionResult Index(string p,int sayfa = 1)
        {
           var değerler = from ürün in ürünStokEntities.URUNLER select ürün;
           if(!string.IsNullOrEmpty(p))
            {
                değerler = değerler.Where(m => m.URUNAD.Contains(p));
            }
           var urunList = değerler.ToList().ToPagedList(sayfa, 6);

            return View(urunList);
        }

        [HttpGet]
        public ActionResult YeniUrun()
        {
            List<SelectListItem> kategorilerim = (from i in ürünStokEntities.KATEGORILER.ToList()
                                                  select new SelectListItem
                                                  {
                                                      Text = i.KATEGORIAD,
                                                      Value = i.KATEGORIID.ToString()
                                                  }).ToList();

            ViewBag.kategori = kategorilerim;
            return View();
        }

        [HttpPost]
        public ActionResult YeniUrun(URUNLER urun)
        {
            if(!ModelState.IsValid)
            {
                return View("YeniUrun");
            }

            using (ÜrünStokDatabaseEntities dbContext = new ÜrünStokDatabaseEntities())
            {
                // Ürünün ait olduğu kategori nesnesini alın
                var ktg = dbContext.KATEGORILER.Where(m => m.KATEGORIID == urun.KATEGORILER.KATEGORIID).FirstOrDefault();
                int i = ürünStokEntities.URUNLER.Count();


                // Eğer ktg null değilse (kategori bulunduysa), urun nesnesinin KATEGORILER özelliğine atanır
                if (ktg != null)
                {
                    urun.KATEGORILER = ktg;
                    urun.URUNID = i+1;

                    // URUNLER tablosuna yeni ürünü ekleyin
                    dbContext.URUNLER.Add(urun);
                    dbContext.SaveChanges();
                }

                // Index sayfasına yönlendirin
                return RedirectToAction("Index");
            }
        }
        public ActionResult Sil(int id)
        {
            var bulunanUrun = ürünStokEntities.URUNLER.Find(id);
            ürünStokEntities.URUNLER.Remove(bulunanUrun);
            ürünStokEntities.SaveChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Urungetir(int id)
        {
            var bulunanUrun = ürünStokEntities.URUNLER.Find(id);
            List<SelectListItem> kategorilerim = (from i in ürünStokEntities.KATEGORILER.ToList()
                                                  select new SelectListItem
                                                  {
                                                      Text = i.KATEGORIAD,
                                                      Value = i.KATEGORIID.ToString()
                                                  }).ToList();
            ViewBag.kategori = kategorilerim;
            return View("UrunGuncelle", bulunanUrun);
        }
        [HttpPost]
        public ActionResult UrunGuncelle(URUNLER urun)
        {
            var bulunanUrun = ürünStokEntities.URUNLER.Find(urun.URUNID);

            bulunanUrun.URUNID = urun.URUNID;
            bulunanUrun.URUNAD = urun.URUNAD;
            bulunanUrun.MARKA = urun.MARKA;
            var ktg = ürünStokEntities.KATEGORILER.Where(m => m.KATEGORIID == urun.KATEGORILER.KATEGORIID).FirstOrDefault();
            bulunanUrun.URUNKATEGORI = (short?)ktg.KATEGORIID;
            bulunanUrun.FIYAT = urun.FIYAT;
            bulunanUrun.STOK = urun.STOK;
            ürünStokEntities.SaveChanges();

            return RedirectToAction("Index");
        }
    }
}

StokUygulamasıMVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-dark bg-dark">
        <div class="container">
            @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Toggle navigation" aria-controls="navbarSupportedContent"
                    aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse d-sm-inline-flex justify-content-between">
                <ul class="navbar-nav flex-grow-1">
                    <li>@Html.ActionLink("Home", "Index", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("About", "About", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home", new { area = "" }, new { @class = "nav-link" })</li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

StokUygulamasıMVC/Views/Shared/_MainLayout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <title>Bootstrap Example</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.4/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>
</head>
<body>

    <nav class="navbar navbar-inverse">
        <div class="container-fluid">
            <div class="navbar-header">
                <a class="navbar-brand" href="#">MVC STOK</a>
            </div>
            <ul class="nav navbar-nav">
                <li class="active">
                    <a href="@Url.Action("Index","Kategori")">Kategoriler</a>
                </li>
                <li class="dropdown">
                <li class="active">
                    <a href="@Url.Action("Index","Urunler")">Ürünler</a>
                </li>
                <li class="dropdown">
                <li class="active">
                    <a href="@Url.Action("Index","Satis")">Satışlar</a>
                </li>
                <li class="dropdown">
                <li class="active">
                    <a href="@Url.Action("Index","Musteri")">Müşteriler</a>
                </li>
                <li class="dropdown">

            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                <li><a href="#"><span class="glyphicon glyphicon-log-in"></span> Login</a></li>
            </ul>
        </div>
    </nav>

    <div class="container">
        @RenderBody()
    </div>
</body>
</html>